version: 0.2

env:
  variables:
    PROJECT: tools
    DOCKER_VERSION: 23.0.6
    MAVEN_IMAGE: 3.9.5-eclipse-temurin-21

phases:
  pre_build:
    commands:
      - REPOSITORY_URI=public.ecr.aws/magicorn
      - TAG_NUMBER="$(git describe --tags --abbrev=0)"
      - echo $CODEBUILD_SOURCE_VERSION
      - echo Checking tool versions...
      - aws --version
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f dockerfiles/deploy -t $REPOSITORY_URI/$PROJECT-deploy:$TAG_NUMBER -t $REPOSITORY_URI/$PROJECT-deploy:latest .
      - docker build -f dockerfiles/debug -t $REPOSITORY_URI/$PROJECT-debug:$TAG_NUMBER -t $REPOSITORY_URI/$PROJECT-debug:latest .
      - docker build -f dockerfiles/maven --build-arg MAVEN_IMAGE=$MAVEN_IMAGE --build-arg DOCKER_VERSION=$DOCKER_VERSION -t $REPOSITORY_URI/$PROJECT-maven:$MAVEN_IMAGE-$TAG_NUMBER -t $REPOSITORY_URI/$PROJECT-maven:$MAVEN_IMAGE-latest .
      - docker build -f dockerfiles/azp-agent -t $REPOSITORY_URI/$PROJECT-azp-agent:$TAG_NUMBER -t $REPOSITORY_URI/$PROJECT-azp-agent:latest .
      - echo Build completed.
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI/$PROJECT-deploy:$TAG_NUMBER
      - docker push $REPOSITORY_URI/$PROJECT-deploy:latest
      - docker push $REPOSITORY_URI/$PROJECT-debug:$TAG_NUMBER
      - docker push $REPOSITORY_URI/$PROJECT-debug:latest
      - docker push $REPOSITORY_URI/$PROJECT-maven:$MAVEN_IMAGE-$TAG_NUMBER
      - docker push $REPOSITORY_URI/$PROJECT-maven:$MAVEN_IMAGE-latest
      - docker push $REPOSITORY_URI/$PROJECT-azp-agent:$TAG_NUMBER
      - docker push $REPOSITORY_URI/$PROJECT-azp-agent:latest
      - echo Post build completed.
      - echo Build passed.